version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: netsec_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

  ftp:
    image: fauria/vsftpd
    container_name: netsec_ftp
    ports:
      - "2121:21"
      - "21000-21010:21000-21010"
    environment:
      - FTP_USER=jessica
      - FTP_PASS=butterfly   # Students will brute-force with Hydra
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
      - PASV_ADDRESS=127.0.0.1
    volumes:
      - ./ftp_data:/home/vsftpd/jessica
    restart: always

  udp_service1:
    image: alpine
    container_name: netsec_udp1
    command: sh -c "apk add --no-cache socat && socat -v udp-recvfrom:9000,fork exec:'/bin/cat'"
    ports:
      - "9000:9000/udp"
    restart: always

  udp_service2:
    image: alpine
    container_name: netsec_udp2
    command: sh -c "apk add --no-cache socat && socat -v udp-recvfrom:9001,fork exec:'/bin/cat'"
    ports:
      - "9001:9001/udp"
    restart: always

  hidden_service:
    image: alpine
    container_name: netsec_hidden
    command: sh -c "apk add --no-cache busybox-extras && while true; do echo 'Running...' | nc -lp 10023; done"
    ports:
      - "10023:10023"
    restart: always
