version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: lab_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - FLAG_HEADER=FLAG{http_header_hidden_flag}

  ftp:
    image: fauria/vsftpd
    container_name: lab_ftp
    ports:
      - "2121:21"
      - "21000-21010:21000-21010"
    environment:
      - FTP_USER=jessica
      - FTP_PASS=butterfly   # Students will brute-force with Hydra
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
      - PASV_ADDRESS=127.0.0.1
    volumes:
      - ./ftp_data:/home/vsftpd/student
    restart: unless-stopped

  udp_service1:
    image: alpine
    container_name: lab_udp1
    command: sh -c "apk add --no-cache socat && socat -v udp-recvfrom:9000,fork exec:'/bin/cat'"
    ports:
      - "9000:9000/udp"
  udp_service2:
    image: alpine
    container_name: lab_udp2
    command: sh -c "apk add --no-cache socat && socat -v udp-recvfrom:9000,fork exec:'/bin/cat'"
    ports:
      - "9001:9001/udp"

  hidden_service:
    image: alpine
    container_name: lab_hidden
    command: sh -c "while true; do echo 'FLAG{hidden_high_port_flag}'; sleep 5; done"
    ports:
      - "10023:10023"

  # ssh:
  #   image: linuxserver/openssh-server
  #   container_name: lab_ssh
  #   ports:
  #     - "2222:2222"
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #     - PASSWORD_ACCESS=true
  #     - USER_NAME=student
  #     - USER_PASSWORD=toor
  #   restart: unless-stopped
