version: '3'
services:
  web:
    image: juice-shop-test:latest
    container_name: web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=juice-shop-config
      - EMAIL=${STUDENT_EMAIL}
      - LAB_ID=web_hacking
      - CTF_KEY=${SECRET}
    volumes:
      - /labs/web/juice-shop-config.yml:/juice-shop/config/juice-shop-config.yml